### PR TITLE
"TimestampClock" class

### PR DESCRIPTION
**Pull request by Turbo87**
This PR adds a second kind of clock service. This service can be throttled to only trigger every `interval` milliseconds and will then update a `time` property with the current timestamp.

In the second commit I've changed the original service to be based on this new kind of service to reduce code duplication. I've kept the original service for now and according to the tests it works just like before. I did however add a deprecation warning that instead of relying on the default `clock` service the user should generate his own via `ember generate clock <name>` instead.

Advantages:
- the timestamp is always directly available via `time` (also as a `Date` in the computed `date` property)
- the throttling is not limited to second, minute, five, quarter and hour
- work is only performed when needed and not *every* second

Disadvantages:
- the user will have to generate a clock instance for his use case since there is no default `clock` service anymore (can be done on install time with default settings though)

@jerel I have not updated the Readme yet since I wanted to know what you think about this first. Feel free to reject these changes, in that case I will extract them into a separate addon. I think the advantages of this approach overweigh the disadvantages, but I'm happy to discuss :)

### CODE REVIEW

**Comment by Turbo87** [comment]
I'd suggest looking at the commits one-by-one to review this. The whole diff looks a bit messy due to some renaming...

**Comment by jerel** [comment]
@Turbo87 I like these changes as it simplifies quite a bit; thanks for the improvements. I'd say carry on with the documentation update and I'll release it as 3.0.0 when finished

**Comment by Turbo87** [comment]
Cool thanks. You could also release it as a 2.x version for now because the
changes are backwards compatible and the old API is properly deprecated. In
3.0 the old/deprecated API should be removed to prevent the overhead.

Jerel Unruh <notifications@github.com> schrieb am Di., 16. Feb. 2016 03:57:

**Comment by Turbo87** [comment]
@jerel I've updated the README now. let me know what you think.

**Comment by jerel** [comment]
@Turbo87 thanks for this! I'll tag it as 2.1.0; I had missed the fact earlier that the `clock` service imported the legacy service.

**Comment by Turbo87** [comment]
cool, thanks!

**Comment by Turbo87** [comment]
@jerel would be awesome if you could update the live demo to reflect the changes

**Comment by Turbo87** [comment]
and `package.json` also needs to be updated ;)

**Comment by jerel** [comment]
@Turbo87 good catch, I absentmindedly tagged locally and published the tag without committing my package.json version change. The demo is up-to-date now too

**Pull request merged**
