### PR TITLE
Several Improvements

### PR DESCRIPTION
**Pull request by Turbo87**
This PR contains several smaller improvements to the codebase. It would probably be best to review them per commit if necessary.

### CODE REVIEW

**Comment by Turbo87** [comment]
@jerel any comments?

**Comment by jerel** [comment]
@Turbo87 thanks for this PR, I'll do my best to get it reviewed on Monday

**Comment by Turbo87** [comment]
@jerel cool thanks!

**Comment by jerel** [comment]
@Turbo87 thanks for the excellent contribution! Your changes have been released as part of v2.0.1

**Comment by Turbo87** [comment]
cool, thanks! I've pushed some followup work into #6, would be awesome if you could also have a look at that.

**Pull request merged**
